begin;

create schema if not exists food_info;

create table if not exists food_info.food_category (
  id integer generated by default as identity primary key,
  parent_id integer default 0,
  name varchar(255) not null,
  sort_order integer default 0
);

create table if not exists food_info.food (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  category_id integer references food_info.food_category(id) on delete set null,
  brand varchar(255),
  description text,
  image_url text,
  status integer default 1,
  created_at timestamp default current_timestamp,
  updated_at timestamp default current_timestamp
);

create index if not exists ix_food_name on food_info.food(lower(name));

create table if not exists food_info.food_nutrition (
  id integer generated by default as identity primary key,
  food_id integer not null references food_info.food(id) on delete cascade,
  unit varchar(64) default '100g',
  calories real not null,
  protein real default 0,
  fat real default 0,
  carbohydrate real default 0,
  dietary_fiber real default 0,
  sugar real default 0,
  sodium real default 0,
  cholesterol real default 0,
  unique(food_id, unit)
);

create index if not exists ix_food_nutrition_food on food_info.food_nutrition(food_id);

create table if not exists food_info.food_serving (
  id integer generated by default as identity primary key,
  food_id integer not null references food_info.food(id) on delete cascade,
  serving_name varchar(255) not null,
  gram_weight real not null,
  unit_type varchar(32) default 'g',
  is_default integer default 0
);

create index if not exists ix_food_serving_food on food_info.food_serving(food_id);

commit;
